"""empty message

Revision ID: 0631745c17f8
Revises: 7115699b2474
Create Date: 2025-08-11 23:47:37.686549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0631745c17f8'
down_revision = '7115699b2474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boardways',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('created_date', sa.String(), nullable=True),
    sa.Column('created_timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boardways')
    # ### end Alembic commands ###
