"""empty message

Revision ID: 63a80d35aea0
Revises: e17988404a75
Create Date: 2025-10-05 15:34:25.293658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a80d35aea0'
down_revision = 'e17988404a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_search_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_search_categories', schema=None) as batch_op:
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
