"""empty message

Revision ID: 7115699b2474
Revises: ef9bfa1115fe
Create Date: 2025-05-25 17:15:45.289836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7115699b2474'
down_revision = 'ef9bfa1115fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_timestamp', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_column('created_timestamp')
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
