"""empty message

Revision ID: 7a5193cc0286
Revises: ce67086e1c8a
Create Date: 2025-09-15 19:37:03.406156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5193cc0286'
down_revision = 'ce67086e1c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_search_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_date', sa.String(), nullable=True),
    sa.Column('created_timestamp', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_search_categories')
    # ### end Alembic commands ###
