"""empty message

Revision ID: 7d2f2fa2888a
Revises: 
Create Date: 2025-05-25 00:03:05.273242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2f2fa2888a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uslis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uslis')
    # ### end Alembic commands ###
