"""empty message

Revision ID: e17988404a75
Revises: 7a5193cc0286
Create Date: 2025-09-25 11:46:30.715819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17988404a75'
down_revision = '7a5193cc0286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_search_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_search_categories', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
