"""empty message

Revision ID: ef9bfa1115fe
Revises: 7d2f2fa2888a
Create Date: 2025-05-25 15:25:03.436247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9bfa1115fe'
down_revision = '7d2f2fa2888a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner', sa.String(length=256), nullable=True),
    sa.Column('privacy', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    # ### end Alembic commands ###
